# 数据集路径配置
data:
  type: 'LEVIR'
  # type: 'WHU'
  # type: 'LEVIR+'
  LEVIR: "E:/CD_datasets/LEVIR-CD"
  # LEVIR: "E:/CD_datasets/LEVIR-CD-0.1"
  LEVIR+: "E:/CD_datasets/LEVIR-CD+"
  WHU: "E:/CD_datasets/WHU-CD"
  # root: "D:/Datasets/SYSU-CD"
  # root: "D:/Datasets/S2Looking"
  # root: "./data_test"

# 模型和训练超参数
model:
  # model_name: "facebook/sam-vit-base"  # 基础模型的名称
  # model_path: "D:/Checkpoints/"
  # model_type: "hiera_b+"
  # checkpoint_path: "E:/CD_Checkpoints/sam2_hiera_base_plus.pt"
  # config: "sam2_configs/sam2_cd_hiera_b+.yaml"
  model_type: "hiera_s"
  checkpoint_path: "E:/CD_Checkpoints/sam2_hiera_small.pt"
  # checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/LEVIR+/hiera_s/model_1000_1_20241031_092430/SAM2_LEVIR+_checkpoint.pth"
  config: "sam2_configs/sam2_cd_hiera_s.yaml"
  # model_type: "hiera_l"
  # checkpoint_path: "E:/CD_Checkpoints/sam2_hiera_large.pt"
  # config: "sam2_configs/sam2_cd_hiera_l.yaml"
  # # checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/LEVIR+/hiera_l/model_1000_1_20241028_113229/SAM2_LEVIR+_checkpoint.pth"

training:
  batch_size: 1        # 批量大小
  learning_rate: 0.00001   # 初始学习率 1e-5
  num_epochs: 1000       # 训练的epoch数量
  device: "cuda"        # 训练设备 ("cuda" 或 "cpu")
  dev_id: 0
  seed: 77              # 随机种子，确保结果可复现
  weight_decay: 0.005
  num_workers: 4

# 日志和输出配置
logging:
  log_dir: "./logs"            # 日志文件目录
  save_dir: "./outputs/"

# 验证和测试配置
validation:
  validate_every: 1     # 每多少个epoch进行一次验证
  save_best_model: True # 是否在验证过程中保存表现最好的模型
