# 数据集路径配置
data:
  type: 'LEVIR'
  # type: 'WHU'
  # type: 'LEVIR+'
  LEVIR: "E:/CD_datasets/LEVIR-CD-0.2-semi"
  LEVIR+: "E:/CD_datasets/LEVIR-CD+"
  WHU: "E:/CD_datasets/WHU-CD"

# 模型和训练超参数
model:
  # model_type: "hiera_b+"
  # checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/LEVIR/model_1000_1_20241015_090807/SAM2_LEVIR_e847_OA99.19_F91.14_IoU84.49.pth"
  # config: "sam2_configs/sam2_cd_hiera_b+.yaml"
  model_type: "hiera_s"
  # checkpoint_path: "E:/CD_Checkpoints/sam2_hiera_small.pt"
  checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/LEVIR/hiera_s/baseline-0.2/model_2000_1_20250102_231611/SAM2_LEVIR_e1909_OA98.55_F86.42_IoU77.31.pth"
  config: "sam2_configs/sam2_cd_hiera_s.yaml"
  # model_type: "hiera_l"
  # config: "sam2_configs/sam2_cd_hiera_l.yaml"
  # # checkpoint_path: "D:/Checkpoints/sam2_hiera_large.pt"
  # # checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/LEVIR/hiera_l/model_1000_1_20241021_193403/SAM2_LEVIR_e627_OA99.19_F91.86_IoU85.51.pth"
  # checkpoint_path: "E:/CD_projects/SAM2-CD/outputs/WHU/hiera_l/model_1000_1_20241023_235817/SAM2_WHU_e333_OA99.74_F88.14_IoU83.09.pth"

training:
  batch_size: 1        # 批量大小
  learning_rate: 0.00001   # 初始学习率 1e-5
  num_epochs: 1000       # 训练的epoch数量
  device: "cuda"        # 训练设备 ("cuda" 或 "cpu")
  dev_id: 0
  seed: 77              # 随机种子，确保结果可复现
  weight_decay: 0.0005
  num_workers: 4

# 日志和输出配置
logging:
  log_dir: "./logs"            # 日志文件目录
  save_dir: "./outputs/"
