# 数据集路径配置
data:
  root: "D:/Datasets/LEVIR-CD"
  # root: "D:/Datasets/WHU-CD"
  # root: "D:/Datasets/SYSU-CD"
  # root: "D:/Datasets/S2Looking"
  # root: "./data_test"
  # train_data_dir: "D:/Datasets/LEVIR-CD/train"
  # val_data_dir: "D:/Datasets/LEVIR-CD/val"
  # test_data_dir: "D:/Datasets/LEVIR-CD/test"

# 模型和训练超参数
model:
  model_name: "facebook/sam-vit-base"  # 基础模型的名称
  model_path: "D:/Checkpoints/"
  # model_type: "hiera_b+"
  # checkpoint_path: "D:/Checkpoints/sam2_hiera_base_plus.pt"
  # # checkpoint_path: "D:/SAM/SAM2-CD/outputs/models/sam2_cd_hiera_b+/model_500_1_20240924_110546/SAM2_LEVIR_400.pth"
  # config: "sam2_configs/sam2_cd_hiera_b+.yaml"
  model_type: "hiera_s"
  checkpoint_path: "D:/Checkpoints/sam2_hiera_small.pt"
  config: "sam2_configs/sam2_cd_hiera_s.yaml"
  # model_type: "hiera_l"
  # # checkpoint_path: "D:/Checkpoints/sam2_hiera_large.pt"
  # config: "sam2_configs/sam2_cd_hiera_l.yaml"
  # checkpoint_path: "D:/Checkpoints/SAM2_LEVIR_e230_OA99.10_F90.73_IoU83.73.pth"

training:
  batch_size: 1        # 批量大小
  learning_rate: 0.00001   # 初始学习率 1e-5
  num_epochs: 1000       # 训练的epoch数量
  device: "cuda"        # 训练设备 ("cuda" 或 "cpu")
  seed: 77              # 随机种子，确保结果可复现

# 日志和输出配置
logging:
  log_dir: "./logs"            # 日志文件目录
#  model_save_dir: "./outputs/models/sam2_cd_hiera_b+"  # 保存微调后模型的目录
  model_save_dir: "./outputs/models/sam2_cd_hiera_s"
  # model_save_dir: "./outputs/models/sam2_cd_hiera_l"
  results_save_dir: "./outputs/results" # 保存测试结果的目录

# 验证和测试配置
validation:
  validate_every: 1     # 每多少个epoch进行一次验证
  save_best_model: True # 是否在验证过程中保存表现最好的模型
